### ISSUE TITLE
JS error: Cannot read property 'digest'

### ISSUE THREAD

**Issue by gablin** [pheditor/pheditor#35]
I tried to use this editor on server, and whenever I try to open a file I get the following error in the web browser:

```
jQuery.Deferred exception: Cannot read property 'digest' of undefined TypeError: Cannot read property 'digest' of undefined
    at sha512 (http://lindaochgabriel.se/fest/pheditor.php:210:25)
    at http://lindaochgabriel.se/fest/pheditor.php:513:6
    at dispatch (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js:5183:27)
    at elemData.handle (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js:4991:28)
    at Object.trigger (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js:8249:12)
    at https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js:8327:17
    at Function.each (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js:354:19)
    at jQuery.fn.init.each (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js:189:17)
    at jQuery.fn.init.trigger (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js:8326:15)
    at HTMLDocument.<anonymous> (http://lindaochgabriel.se/fest/pheditor.php:576:15) undefined

jQuery.Deferred.exceptionHook | @ | jquery.js:3818
-- | -- | --
  | process | @ | jquery.js:3606
  | setTimeout (async) |   |  
  | (anonymous) | @ | jquery.js:3640
  | fire | @ | jquery.js:3268
  | fireWith | @ | jquery.js:3398
  | fire | @ | jquery.js:3406
  | fire | @ | jquery.js:3268
  | fireWith | @ | jquery.js:3398
  | ready | @ | jquery.js:3878
  | completed | @ | jquery.js:3888
```

I tried with both Chrome and Firefox, to no avail. I also tried accessing all cloudflare files and all were working, so I don't know what's the problem here...

**Comment by soundspawn** [comment]
You have to be on https for crypto (a requirement) to work

https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle
Crypto.subtle returns undefined in http, and errors ensue
